import Foundation

/// Generates a complete bundle host app project and builds it into a signed .app (and optionally .dmg).
enum BuildEngine {
    typealias OnEntry = @Sendable (BuildLog.Entry) -> Void

    @discardableResult
    static func run(
        definition: BundleDefinition,
        modules: [ModuleEntry],
        onEntry: @escaping OnEntry
    ) async -> Bool {
        let log = Logger(onEntry: onEntry)
        let workDir = FileManager.default.temporaryDirectory
            .appending(path: "bundler-\(definition.slug)-\(UUID().uuidString.prefix(8))", directoryHint: .isDirectory)

        do {
            log.info("Preparing \(definition.name)…")
            try FileManager.default.createDirectory(at: workDir, withIntermediateDirectories: true)
            defer { try? FileManager.default.removeItem(at: workDir) }

            // 1. Generate project files
            try generate(definition: definition, modules: modules, in: workDir, log: log)

            // 2. swift build -c release
            try await shell("swift build -c release", in: workDir, log: log)

            // 3. Assemble .app bundle
            let appURL = try assemble(definition: definition, modules: modules, in: workDir, log: log)

            // 4. Codesign
            try await codesign(appURL: appURL, identity: definition.signingIdentity, log: log)

            // 5. Copy to output directory
            let outDir = URL(fileURLWithPath: (definition.outputDirectory as NSString).expandingTildeInPath)
            try FileManager.default.createDirectory(at: outDir, withIntermediateDirectories: true)
            let destApp = outDir.appending(path: "\(definition.executableName).app")
            try? FileManager.default.removeItem(at: destApp)
            try FileManager.default.copyItem(at: appURL, to: destApp)
            log.success("Built \(destApp.path)")

            // 6. Optional DMG
            if definition.buildDMG {
                try await DMGEngine.run(appURL: destApp, outputDir: outDir, log: log)
            }

            return true
        } catch {
            log.error(error.localizedDescription)
            return false
        }
    }

    // MARK: - Code generation

    private static func generate(
        definition: BundleDefinition,
        modules: [ModuleEntry],
        in dir: URL,
        log: Logger
    ) throws {
        log.info("Generating project…")

        let srcDir = dir.appending(path: "Sources/\(definition.executableName)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: srcDir, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: dir.appending(path: "Resources", directoryHint: .isDirectory), withIntermediateDirectories: true)

        try packageSwift(definition: definition, modules: modules).write(
            to: dir.appending(path: "Package.swift"), atomically: true, encoding: .utf8)

        try appSwift(definition: definition, modules: modules).write(
            to: srcDir.appending(path: "BundleApp.swift"), atomically: true, encoding: .utf8)

        try windowSwift(definition: definition, modules: modules).write(
            to: srcDir.appending(path: "BundleWindow.swift"), atomically: true, encoding: .utf8)

        try infoPlist(definition: definition).write(
            to: dir.appending(path: "Resources/Info.plist"), atomically: true, encoding: .utf8)
    }

    private static func packageSwift(definition: BundleDefinition, modules: [ModuleEntry]) -> String {
        let deps = modules.map { "        .package(path: \"\($0.path)\")," }.joined(separator: "\n")
        let targets = modules.map { "            \"\($0.targetName)\"," }.joined(separator: "\n")
        return """
        // swift-tools-version: 6.1
        import PackageDescription

        // Auto-generated by Bundler — do not edit.
        let package = Package(
            name: "\(definition.executableName)",
            platforms: [.macOS("26.0")],
            dependencies: [
                .package(path: "../iUX"),
        \(deps)
            ],
            targets: [
                .executableTarget(
                    name: "\(definition.executableName)",
                    dependencies: [
                        "iUX",
        \(targets)
                    ],
                    path: "Sources/\(definition.executableName)"
                ),
            ]
        )
        """
    }

    private static func appSwift(definition: BundleDefinition, modules: [ModuleEntry]) -> String {
        let imports = modules.map { "import \($0.targetName)" }.joined(separator: "\n")
        let moduleInits = modules.map { "    let \($0.displayName.lowercased()) = \($0.targetName).module()" }.joined(separator: "\n")
        let allModules = modules.map { $0.displayName.lowercased() }.joined(separator: ", ")
        return """
        // Auto-generated by Bundler — do not edit.
        import SwiftUI
        import iUX
        \(imports)

        @main
        struct BundleApp: App {
            @NSApplicationDelegateAdaptor(BundleDelegate.self) private var delegate

            var body: some Scene {
                Window("\(definition.name)", id: "main") {
                    BundleWindow(model: delegate.model)
                }
                .defaultSize(width: 820, height: 560)
                .windowResizability(.contentSize)
            }
        }

        @MainActor
        final class BundleDelegate: NSObject, NSApplicationDelegate {
        \(moduleInits)

            lazy var model: BundleWindowModel = .init(modules: [\(allModules)])

            func applicationDidFinishLaunching(_ notification: Notification) {
                model.startAll()
            }

            func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool { true }
        }
        """
    }

    private static func windowSwift(definition: BundleDefinition, modules: [ModuleEntry]) -> String {
        """
        // Auto-generated by Bundler — do not edit.
        import SwiftUI
        import iUX

        @MainActor
        @Observable
        final class BundleWindowModel {
            let modules: [any AppModule]
            var selection: (any AppModule)?

            init(modules: [any AppModule]) {
                self.modules = modules
                self.selection = modules.first
            }

            func startAll() {
                modules.forEach { $0.start() }
            }
        }

        struct BundleWindow: View {
            let model: BundleWindowModel

            var body: some View {
                NavigationSplitView {
                    List(model.modules, id: \\.moduleID, selection: .constant(nil as String?)) { module in
                        Label(module.displayName, systemImage: module.symbolName)
                    }
                    .listStyle(.sidebar)
                    .navigationTitle("\(definition.name)")
                } detail: {
                    if let selected = model.selection {
                        selected.settingsView()
                    } else {
                        ContentUnavailableView("Select an app", systemImage: "sidebar.left")
                    }
                }
            }
        }
        """
    }

    private static func infoPlist(definition: BundleDefinition) -> String {
        """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>\(definition.executableName)</string>
            <key>CFBundleIdentifier</key>
            <string>\(definition.bundleID)</string>
            <key>CFBundleName</key>
            <string>\(definition.name)</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleVersion</key>
            <string>1</string>
            <key>LSMinimumSystemVersion</key>
            <string>26.0</string>
            <key>NSHumanReadableCopyright</key>
            <string>anti-ltd</string>
        </dict>
        </plist>
        """
    }

    // MARK: - Assembly

    private static func assemble(
        definition: BundleDefinition,
        modules: [ModuleEntry],
        in dir: URL,
        log: Logger
    ) throws -> URL {
        log.info("Assembling .app…")
        let appURL = dir.appending(path: "\(definition.executableName).app")
        let macOS   = appURL.appending(path: "Contents/MacOS")
        let resources = appURL.appending(path: "Contents/Resources")
        try FileManager.default.createDirectory(at: macOS, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: resources, withIntermediateDirectories: true)

        let binary = dir.appending(path: ".build/release/\(definition.executableName)")
        try FileManager.default.copyItem(at: binary, to: macOS.appending(path: definition.executableName))
        try FileManager.default.copyItem(
            at: dir.appending(path: "Resources/Info.plist"),
            to: appURL.appending(path: "Contents/Info.plist")
        )
        return appURL
    }

    // MARK: - Codesign

    private static func codesign(appURL: URL, identity: String, log: Logger) async throws {
        log.cmd("codesign --force --deep --sign \"\(identity)\" \(appURL.path)")
        try await shell("codesign --force --deep --sign \"\(identity)\" \"\(appURL.path)\"", log: log)
    }

    // MARK: - Shell

    static func shell(_ command: String, in dir: URL? = nil, log: Logger) async throws {
        log.cmd(command)
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/zsh")
        process.arguments = ["-c", command]
        if let dir { process.currentDirectoryURL = dir }

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError  = pipe

        try process.run()

        for try await line in pipe.fileHandleForReading.bytes.lines {
            log.output(line)
        }

        process.waitUntilExit()
        if process.terminationStatus != 0 {
            throw BuildError.nonZeroExit(Int(process.terminationStatus))
        }
    }

    enum BuildError: Error, LocalizedError {
        case nonZeroExit(Int)
        var errorDescription: String? {
            if case .nonZeroExit(let code) = self { return "Command failed (exit \(code))" }
            return nil
        }
    }

    // MARK: - Logger shim

    struct Logger {
        let onEntry: OnEntry
        func info(_ s: String)    { onEntry(.init(kind: .info,    text: s)) }
        func cmd(_ s: String)     { onEntry(.init(kind: .command, text: s)) }
        func output(_ s: String)  { onEntry(.init(kind: .output,  text: s)) }
        func success(_ s: String) { onEntry(.init(kind: .success, text: s)) }
        func error(_ s: String)   { onEntry(.init(kind: .error,   text: s)) }
    }
}
